// Auto-generated from util/gen_log_type.ts
// DO NOT EDIT THIS FILE DIRECTLY

export type LogDefinitionTypes =
  | 'GameLog'
  | 'ChangeZone'
  | 'ChangedPlayer'
  | 'AddedCombatant'
  | 'RemovedCombatant'
  | 'PartyList'
  | 'PlayerStats'
  | 'StartsUsing'
  | 'Ability'
  | 'NetworkAOEAbility'
  | 'NetworkCancelAbility'
  | 'NetworkDoT'
  | 'WasDefeated'
  | 'GainsEffect'
  | 'HeadMarker'
  | 'NetworkRaidMarker'
  | 'NetworkTargetMarker'
  | 'LosesEffect'
  | 'NetworkGauge'
  | 'NetworkWorld'
  | 'ActorControl'
  | 'NameToggle'
  | 'Tether'
  | 'LimitBreak'
  | 'NetworkEffectResult'
  | 'StatusEffect'
  | 'NetworkUpdateHP'
  | 'Map'
  | 'SystemLogMessage'
  | 'StatusList3'
  | 'ParserInfo'
  | 'ProcessInfo'
  | 'Debug'
  | 'PacketDump'
  | 'Version'
  | 'Error'
  | 'None'
  | 'LineRegistration'
  | 'MapEffect'
  | 'FateDirector'
  | 'CEDirector';

export type NetFields = {
  GameLog: { 'type': 0; 'timestamp': 1; 'code': 2; 'name': 3; 'line': 4 };
  ChangeZone: { 'type': 0; 'timestamp': 1; 'id': 2; 'name': 3 };
  ChangedPlayer: { 'type': 0; 'timestamp': 1; 'id': 2; 'name': 3 };
  AddedCombatant: {
    'type': 0;
    'timestamp': 1;
    'id': 2;
    'name': 3;
    'job': 4;
    'level': 5;
    'ownerId': 6;
    'worldId': 7;
    'world': 8;
    'npcNameId': 9;
    'npcBaseId': 10;
    'currentHp': 11;
    'hp': 12;
    'currentMp': 13;
    'mp': 14;
    'x': 17;
    'y': 18;
    'z': 19;
    'heading': 20;
  };
  RemovedCombatant: {
    'type': 0;
    'timestamp': 1;
    'id': 2;
    'name': 3;
    'job': 4;
    'level': 5;
    'owner': 6;
    'world': 8;
    'npcNameId': 9;
    'npcBaseId': 10;
    'hp': 12;
    'x': 17;
    'y': 18;
    'z': 19;
    'heading': 20;
  };
  PartyList: {
    'type': 0;
    'timestamp': 1;
    'partyCount': 2;
    'id0': 3;
    'id1': 4;
    'id2': 5;
    'id3': 6;
    'id4': 7;
    'id5': 8;
    'id6': 9;
    'id7': 10;
    'id8': 11;
    'id9': 12;
    'id10': 13;
    'id11': 14;
    'id12': 15;
    'id13': 16;
    'id14': 17;
    'id15': 18;
    'id16': 19;
    'id17': 20;
    'id18': 21;
    'id19': 22;
    'id20': 23;
    'id21': 24;
    'id22': 25;
    'id23': 26;
  };
  PlayerStats: {
    'type': 0;
    'timestamp': 1;
    'job': 2;
    'strength': 3;
    'dexterity': 4;
    'vitality': 5;
    'intelligence': 6;
    'mind': 7;
    'piety': 8;
    'attackPower': 9;
    'directHit': 10;
    'criticalHit': 11;
    'attackMagicPotency': 12;
    'healMagicPotency': 13;
    'determination': 14;
    'skillSpeed': 15;
    'spellSpeed': 16;
    'tenacity': 18;
    'localContentId': 19;
  };
  StartsUsing: {
    'type': 0;
    'timestamp': 1;
    'sourceId': 2;
    'source': 3;
    'id': 4;
    'ability': 5;
    'targetId': 6;
    'target': 7;
    'castTime': 8;
    'x': 9;
    'y': 10;
    'z': 11;
    'heading': 12;
  };
  Ability: {
    'type': 0;
    'timestamp': 1;
    'sourceId': 2;
    'source': 3;
    'id': 4;
    'ability': 5;
    'targetId': 6;
    'target': 7;
    'flags': 8;
    'damage': 9;
    'targetCurrentHp': 24;
    'targetMaxHp': 25;
    'targetCurrentMp': 26;
    'targetMaxMp': 27;
    'targetX': 30;
    'targetY': 31;
    'targetZ': 32;
    'targetHeading': 33;
    'currentHp': 34;
    'maxHp': 35;
    'currentMp': 36;
    'maxMp': 37;
    'x': 40;
    'y': 41;
    'z': 42;
    'heading': 43;
    'sequence': 44;
    'targetIndex': 45;
    'targetCount': 46;
  };
  NetworkAOEAbility: {
    'type': 0;
    'timestamp': 1;
    'sourceId': 2;
    'source': 3;
    'id': 4;
    'ability': 5;
    'targetId': 6;
    'target': 7;
    'flags': 8;
    'damage': 9;
    'targetCurrentHp': 24;
    'targetMaxHp': 25;
    'targetCurrentMp': 26;
    'targetMaxMp': 27;
    'targetX': 30;
    'targetY': 31;
    'targetZ': 32;
    'targetHeading': 33;
    'currentHp': 34;
    'maxHp': 35;
    'currentMp': 36;
    'maxMp': 37;
    'x': 40;
    'y': 41;
    'z': 42;
    'heading': 43;
    'sequence': 44;
    'targetIndex': 45;
    'targetCount': 46;
  };
  NetworkCancelAbility: {
    'type': 0;
    'timestamp': 1;
    'sourceId': 2;
    'source': 3;
    'id': 4;
    'name': 5;
    'reason': 6;
  };
  NetworkDoT: {
    'type': 0;
    'timestamp': 1;
    'id': 2;
    'name': 3;
    'which': 4;
    'effectId': 5;
    'damage': 6;
    'currentHp': 7;
    'maxHp': 8;
    'currentMp': 9;
    'maxMp': 10;
    'x': 13;
    'y': 14;
    'z': 15;
    'heading': 16;
  };
  WasDefeated: {
    'type': 0;
    'timestamp': 1;
    'targetId': 2;
    'target': 3;
    'sourceId': 4;
    'source': 5;
  };
  GainsEffect: {
    'type': 0;
    'timestamp': 1;
    'effectId': 2;
    'effect': 3;
    'duration': 4;
    'sourceId': 5;
    'source': 6;
    'targetId': 7;
    'target': 8;
    'count': 9;
    'targetMaxHp': 10;
    'sourceMaxHp': 11;
  };
  HeadMarker: { 'type': 0; 'timestamp': 1; 'targetId': 2; 'target': 3; 'id': 6 };
  NetworkRaidMarker: {
    'type': 0;
    'timestamp': 1;
    'operation': 2;
    'waymark': 3;
    'id': 4;
    'name': 5;
    'x': 6;
    'y': 7;
    'z': 8;
  };
  NetworkTargetMarker: {
    'type': 0;
    'timestamp': 1;
    'operation': 2;
    'waymark': 3;
    'id': 4;
    'name': 5;
    'targetId': 6;
    'targetName': 7;
  };
  LosesEffect: {
    'type': 0;
    'timestamp': 1;
    'effectId': 2;
    'effect': 3;
    'sourceId': 5;
    'source': 6;
    'targetId': 7;
    'target': 8;
    'count': 9;
  };
  NetworkGauge: {
    'type': 0;
    'timestamp': 1;
    'id': 2;
    'data0': 3;
    'data1': 4;
    'data2': 5;
    'data3': 6;
  };
  NetworkWorld: { 'type': 0; 'timestamp': 1 };
  ActorControl: {
    'type': 0;
    'timestamp': 1;
    'instance': 2;
    'command': 3;
    'data0': 4;
    'data1': 5;
    'data2': 6;
    'data3': 7;
  };
  NameToggle: {
    'type': 0;
    'timestamp': 1;
    'id': 2;
    'name': 3;
    'targetId': 4;
    'targetName': 5;
    'toggle': 6;
  };
  Tether: {
    'type': 0;
    'timestamp': 1;
    'sourceId': 2;
    'source': 3;
    'targetId': 4;
    'target': 5;
    'id': 8;
  };
  LimitBreak: { 'type': 0; 'timestamp': 1; 'valueHex': 2; 'bars': 3 };
  NetworkEffectResult: {
    'type': 0;
    'timestamp': 1;
    'id': 2;
    'name': 3;
    'sequenceId': 4;
    'currentHp': 5;
    'maxHp': 6;
    'currentMp': 7;
    'maxMp': 8;
    'x': 11;
    'y': 12;
    'z': 13;
    'heading': 14;
  };
  StatusEffect: {
    'type': 0;
    'timestamp': 1;
    'targetId': 2;
    'target': 3;
    'jobLevelData': 4;
    'hp': 5;
    'maxHp': 6;
    'mp': 7;
    'maxMp': 8;
    'x': 11;
    'y': 12;
    'z': 13;
    'heading': 14;
    'data0': 15;
    'data1': 16;
    'data2': 17;
    'data3': 18;
    'data4': 19;
    'data5': 20;
  };
  NetworkUpdateHP: {
    'type': 0;
    'timestamp': 1;
    'id': 2;
    'name': 3;
    'currentHp': 4;
    'maxHp': 5;
    'currentMp': 6;
    'maxMp': 7;
    'x': 10;
    'y': 11;
    'z': 12;
    'heading': 13;
  };
  Map: { 'type': 0; 'timestamp': 1; 'id': 2; 'regionName': 3; 'placeName': 4; 'placeNameSub': 5 };
  SystemLogMessage: {
    'type': 0;
    'timestamp': 1;
    'instance': 2;
    'id': 3;
    'param0': 4;
    'param1': 5;
    'param2': 6;
  };
  StatusList3: { 'type': 0; 'timestamp': 1; 'id': 2; 'name': 3 };
  ParserInfo: { 'type': 0; 'timestamp': 1 };
  ProcessInfo: { 'type': 0; 'timestamp': 1 };
  Debug: { 'type': 0; 'timestamp': 1 };
  PacketDump: { 'type': 0; 'timestamp': 1 };
  Version: { 'type': 0; 'timestamp': 1 };
  Error: { 'type': 0; 'timestamp': 1 };
  None: { 'type': 0; 'timestamp': 1 };
  LineRegistration: { 'type': 0; 'timestamp': 1; 'id': 2; 'source': 3; 'version': 4 };
  MapEffect: {
    'type': 0;
    'timestamp': 1;
    'instance': 2;
    'flags': 3;
    'location': 4;
    'data0': 5;
    'data1': 6;
  };
  FateDirector: { 'type': 0; 'timestamp': 1; 'category': 2; 'fateId': 4; 'progress': 5 };
  CEDirector: {
    'type': 0;
    'timestamp': 1;
    'popTime': 2;
    'timeRemaining': 3;
    'ceKey': 5;
    'numPlayers': 6;
    'status': 7;
    'progress': 9;
  };
};

export type NetFieldsReverse = {
  GameLog: {
    0: 'type';
    1: 'timestamp';
    2: 'code';
    3: 'name';
    4: 'line';
  };
  ChangeZone: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'name';
  };
  ChangedPlayer: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'name';
  };
  AddedCombatant: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'name';
    4: 'job';
    5: 'level';
    6: 'ownerId';
    7: 'worldId';
    8: 'world';
    9: 'npcNameId';
    10: 'npcBaseId';
    11: 'currentHp';
    12: 'hp';
    13: 'currentMp';
    14: 'mp';
    17: 'x';
    18: 'y';
    19: 'z';
    20: 'heading';
  };
  RemovedCombatant: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'name';
    4: 'job';
    5: 'level';
    6: 'owner';
    8: 'world';
    9: 'npcNameId';
    10: 'npcBaseId';
    12: 'hp';
    17: 'x';
    18: 'y';
    19: 'z';
    20: 'heading';
  };
  PartyList: {
    0: 'type';
    1: 'timestamp';
    2: 'partyCount';
    3: 'id0';
    4: 'id1';
    5: 'id2';
    6: 'id3';
    7: 'id4';
    8: 'id5';
    9: 'id6';
    10: 'id7';
    11: 'id8';
    12: 'id9';
    13: 'id10';
    14: 'id11';
    15: 'id12';
    16: 'id13';
    17: 'id14';
    18: 'id15';
    19: 'id16';
    20: 'id17';
    21: 'id18';
    22: 'id19';
    23: 'id20';
    24: 'id21';
    25: 'id22';
    26: 'id23';
  };
  PlayerStats: {
    0: 'type';
    1: 'timestamp';
    2: 'job';
    3: 'strength';
    4: 'dexterity';
    5: 'vitality';
    6: 'intelligence';
    7: 'mind';
    8: 'piety';
    9: 'attackPower';
    10: 'directHit';
    11: 'criticalHit';
    12: 'attackMagicPotency';
    13: 'healMagicPotency';
    14: 'determination';
    15: 'skillSpeed';
    16: 'spellSpeed';
    18: 'tenacity';
    19: 'localContentId';
  };
  StartsUsing: {
    0: 'type';
    1: 'timestamp';
    2: 'sourceId';
    3: 'source';
    4: 'id';
    5: 'ability';
    6: 'targetId';
    7: 'target';
    8: 'castTime';
    9: 'x';
    10: 'y';
    11: 'z';
    12: 'heading';
  };
  Ability: {
    0: 'type';
    1: 'timestamp';
    2: 'sourceId';
    3: 'source';
    4: 'id';
    5: 'ability';
    6: 'targetId';
    7: 'target';
    8: 'flags';
    9: 'damage';
    24: 'targetCurrentHp';
    25: 'targetMaxHp';
    26: 'targetCurrentMp';
    27: 'targetMaxMp';
    30: 'targetX';
    31: 'targetY';
    32: 'targetZ';
    33: 'targetHeading';
    34: 'currentHp';
    35: 'maxHp';
    36: 'currentMp';
    37: 'maxMp';
    40: 'x';
    41: 'y';
    42: 'z';
    43: 'heading';
    44: 'sequence';
    45: 'targetIndex';
    46: 'targetCount';
  };
  NetworkAOEAbility: {
    0: 'type';
    1: 'timestamp';
    2: 'sourceId';
    3: 'source';
    4: 'id';
    5: 'ability';
    6: 'targetId';
    7: 'target';
    8: 'flags';
    9: 'damage';
    24: 'targetCurrentHp';
    25: 'targetMaxHp';
    26: 'targetCurrentMp';
    27: 'targetMaxMp';
    30: 'targetX';
    31: 'targetY';
    32: 'targetZ';
    33: 'targetHeading';
    34: 'currentHp';
    35: 'maxHp';
    36: 'currentMp';
    37: 'maxMp';
    40: 'x';
    41: 'y';
    42: 'z';
    43: 'heading';
    44: 'sequence';
    45: 'targetIndex';
    46: 'targetCount';
  };
  NetworkCancelAbility: {
    0: 'type';
    1: 'timestamp';
    2: 'sourceId';
    3: 'source';
    4: 'id';
    5: 'name';
    6: 'reason';
  };
  NetworkDoT: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'name';
    4: 'which';
    5: 'effectId';
    6: 'damage';
    7: 'currentHp';
    8: 'maxHp';
    9: 'currentMp';
    10: 'maxMp';
    13: 'x';
    14: 'y';
    15: 'z';
    16: 'heading';
  };
  WasDefeated: {
    0: 'type';
    1: 'timestamp';
    2: 'targetId';
    3: 'target';
    4: 'sourceId';
    5: 'source';
  };
  GainsEffect: {
    0: 'type';
    1: 'timestamp';
    2: 'effectId';
    3: 'effect';
    4: 'duration';
    5: 'sourceId';
    6: 'source';
    7: 'targetId';
    8: 'target';
    9: 'count';
    10: 'targetMaxHp';
    11: 'sourceMaxHp';
  };
  HeadMarker: {
    0: 'type';
    1: 'timestamp';
    2: 'targetId';
    3: 'target';
    6: 'id';
  };
  NetworkRaidMarker: {
    0: 'type';
    1: 'timestamp';
    2: 'operation';
    3: 'waymark';
    4: 'id';
    5: 'name';
    6: 'x';
    7: 'y';
    8: 'z';
  };
  NetworkTargetMarker: {
    0: 'type';
    1: 'timestamp';
    2: 'operation';
    3: 'waymark';
    4: 'id';
    5: 'name';
    6: 'targetId';
    7: 'targetName';
  };
  LosesEffect: {
    0: 'type';
    1: 'timestamp';
    2: 'effectId';
    3: 'effect';
    5: 'sourceId';
    6: 'source';
    7: 'targetId';
    8: 'target';
    9: 'count';
  };
  NetworkGauge: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'data0';
    4: 'data1';
    5: 'data2';
    6: 'data3';
  };
  NetworkWorld: {
    0: 'type';
    1: 'timestamp';
  };
  ActorControl: {
    0: 'type';
    1: 'timestamp';
    2: 'instance';
    3: 'command';
    4: 'data0';
    5: 'data1';
    6: 'data2';
    7: 'data3';
  };
  NameToggle: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'name';
    4: 'targetId';
    5: 'targetName';
    6: 'toggle';
  };
  Tether: {
    0: 'type';
    1: 'timestamp';
    2: 'sourceId';
    3: 'source';
    4: 'targetId';
    5: 'target';
    8: 'id';
  };
  LimitBreak: {
    0: 'type';
    1: 'timestamp';
    2: 'valueHex';
    3: 'bars';
  };
  NetworkEffectResult: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'name';
    4: 'sequenceId';
    5: 'currentHp';
    6: 'maxHp';
    7: 'currentMp';
    8: 'maxMp';
    11: 'x';
    12: 'y';
    13: 'z';
    14: 'heading';
  };
  StatusEffect: {
    0: 'type';
    1: 'timestamp';
    2: 'targetId';
    3: 'target';
    4: 'jobLevelData';
    5: 'hp';
    6: 'maxHp';
    7: 'mp';
    8: 'maxMp';
    11: 'x';
    12: 'y';
    13: 'z';
    14: 'heading';
    15: 'data0';
    16: 'data1';
    17: 'data2';
    18: 'data3';
    19: 'data4';
    20: 'data5';
  };
  NetworkUpdateHP: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'name';
    4: 'currentHp';
    5: 'maxHp';
    6: 'currentMp';
    7: 'maxMp';
    10: 'x';
    11: 'y';
    12: 'z';
    13: 'heading';
  };
  Map: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'regionName';
    4: 'placeName';
    5: 'placeNameSub';
  };
  SystemLogMessage: {
    0: 'type';
    1: 'timestamp';
    2: 'instance';
    3: 'id';
    4: 'param0';
    5: 'param1';
    6: 'param2';
  };
  StatusList3: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'name';
  };
  ParserInfo: {
    0: 'type';
    1: 'timestamp';
  };
  ProcessInfo: {
    0: 'type';
    1: 'timestamp';
  };
  Debug: {
    0: 'type';
    1: 'timestamp';
  };
  PacketDump: {
    0: 'type';
    1: 'timestamp';
  };
  Version: {
    0: 'type';
    1: 'timestamp';
  };
  Error: {
    0: 'type';
    1: 'timestamp';
  };
  None: {
    0: 'type';
    1: 'timestamp';
  };
  LineRegistration: {
    0: 'type';
    1: 'timestamp';
    2: 'id';
    3: 'source';
    4: 'version';
  };
  MapEffect: {
    0: 'type';
    1: 'timestamp';
    2: 'instance';
    3: 'flags';
    4: 'location';
    5: 'data0';
    6: 'data1';
  };
  FateDirector: {
    0: 'type';
    1: 'timestamp';
    2: 'category';
    4: 'fateId';
    5: 'progress';
  };
  CEDirector: {
    0: 'type';
    1: 'timestamp';
    2: 'popTime';
    3: 'timeRemaining';
    5: 'ceKey';
    6: 'numPlayers';
    7: 'status';
    9: 'progress';
  };
};
